export interface Traducao {
    palavra: string;
    traducaoTupi: string;
    traducaoYanomami: string;
    traducaoXavante: string;
    id: number
}
export const Traducoes: Traducao[] = [
    { id: 0, palavra: 'amor', traducaoTupi: 'ahen', traducaoYanomami: 'heta', traducaoXavante: 'adzan' },
    { id: 1, palavra: 'terra', traducaoTupi: 'ahu', traducaoYanomami: 'heno', traducaoXavante: 'waime' },
    { id: 2, palavra: 'sol', traducaoTupi: 'araci', traducaoYanomami: 'shama', traducaoXavante: 'hodzi' },
    { id: 3, palavra: 'lua', traducaoTupi: 'jara', traducaoYanomami: 'apema', traducaoXavante: 'itê' },
    { id: 4, palavra: 'morte', traducaoTupi: 'manu', traducaoYanomami: 'peka', traducaoXavante: 'iroda' },
    { id: 5, palavra: 'fogo', traducaoTupi: 'tatá', traducaoYanomami: 'waka', traducaoXavante: 'dzaw' },
    { id: 6, palavra: 'água', traducaoTupi: 'y', traducaoYanomami: 'shora', traducaoXavante: 'dzawe' },
    { id: 7, palavra: 'floresta', traducaoTupi: 'ka’a', traducaoYanomami: 'amo', traducaoXavante: 'mara' },
    { id: 8, palavra: 'montanha', traducaoTupi: 'ybyty', traducaoYanomami: 'amewa', traducaoXavante: 'katõ' },
    { id: 9, palavra: 'chuva', traducaoTupi: 'amaná', traducaoYanomami: 'pema', traducaoXavante: 'wahé' },
    { id: 10, palavra: 'vento', traducaoTupi: 'karú', traducaoYanomami: 'shoko', traducaoXavante: 'irawa' },
    { id: 11, palavra: 'animal', traducaoTupi: 'jagu', traducaoYanomami: 'yema', traducaoXavante: 'xo' },
    { id: 12, palavra: 'pedra', traducaoTupi: 'ita', traducaoYanomami: 'amo', traducaoXavante: 'awa' },
    { id: 13, palavra: 'estrela', traducaoTupi: 'tara', traducaoYanomami: 'tuara', traducaoXavante: 'ure' },
    { id: 14, palavra: 'coração', traducaoTupi: 'açu', traducaoYanomami: 'hemi', traducaoXavante: 'pako' },
    { id: 15, palavra: 'mulher', traducaoTupi: 'kunhã', traducaoYanomami: 'nammi', traducaoXavante: 'tawé' },
    { id: 16, palavra: 'homem', traducaoTupi: 'abá', traducaoYanomami: 'yano', traducaoXavante: 'kato' },
    { id: 17, palavra: 'rio', traducaoTupi: 'pará', traducaoYanomami: 'uhri', traducaoXavante: 'wara' },
    { id: 18, palavra: 'peixe', traducaoTupi: 'pirá', traducaoYanomami: 'muhe', traducaoXavante: 'iwawê' },
    { id: 19, palavra: 'pássaro', traducaoTupi: 'guyra', traducaoYanomami: 'yuna', traducaoXavante: 'iká' },
    { id: 20, palavra: 'casa', traducaoTupi: 'oka', traducaoYanomami: 'noa', traducaoXavante: 'wasé' },
    { id: 21, palavra: 'caminho', traducaoTupi: 'pe', traducaoYanomami: 'wara', traducaoXavante: 'dji' },
    { id: 22, palavra: 'dia', traducaoTupi: 'ara', traducaoYanomami: 'sama', traducaoXavante: 'rodi' },
    { id: 23, palavra: 'noite', traducaoTupi: 'pyta', traducaoYanomami: 'kuhi', traducaoXavante: 'arehe' },
    { id: 24, palavra: 'felicidade', traducaoTupi: 'morubixaba', traducaoYanomami: 'himi', traducaoXavante: 'awi' },
    { id: 25, palavra: 'alma', traducaoTupi: 'ang', traducaoYanomami: 'hera', traducaoXavante: 'peka' },
    { id: 26, palavra: 'sombra', traducaoTupi: 'mbae', traducaoYanomami: 'hemu', traducaoXavante: 'iti' },
    { id: 27, palavra: 'luz', traducaoTupi: 'kaya', traducaoYanomami: 'hawa', traducaoXavante: 'dara' },
    { id: 28, palavra: 'cabeça', traducaoTupi: 'akanga', traducaoYanomami: 'yako', traducaoXavante: 'bihé' },
    { id: 29, palavra: 'paz', traducaoTupi: 'mokoi', traducaoYanomami: 'peki', traducaoXavante: 'maká' },
    { id: 30, palavra: 'força', traducaoTupi: 'pora', traducaoYanomami: 'eti', traducaoXavante: 'kaú' },
    { id: 31, palavra: 'sangue', traducaoTupi: 'ruguy', traducaoYanomami: 'homi', traducaoXavante: 'mama' },
    { id: 32, palavra: 'flor', traducaoTupi: 'mboty', traducaoYanomami: 'ura', traducaoXavante: 'kema' },
    { id: 33, palavra: 'amigo', traducaoTupi: 'ayvu', traducaoYanomami: 'peho', traducaoXavante: 'nema' },
    { id: 34, palavra: 'tempo', traducaoTupi: 'koe', traducaoYanomami: 'peha', traducaoXavante: 'hure' },
    { id: 35, palavra: 'nuvem', traducaoTupi: 'arabá', traducaoYanomami: 'muhe', traducaoXavante: 'ratu' },
    { id: 36, palavra: 'mãe', traducaoTupi: 'sy', traducaoYanomami: 'hema', traducaoXavante: 'aye' },
    { id: 37, palavra: 'pai', traducaoTupi: 'tuba', traducaoYanomami: 'woa', traducaoXavante: 'pana' },
    { id: 38, palavra: 'filho', traducaoTupi: 'memó', traducaoYanomami: 'yene', traducaoXavante: 'muro' },
    { id: 39, palavra: 'guerra', traducaoTupi: 'monhangara', traducaoYanomami: 'keno', traducaoXavante: 'dzina' },
    { id: 40, palavra: 'espírito', traducaoTupi: 'angüera', traducaoYanomami: 'hara', traducaoXavante: 'kopi' },
    { id: 41, palavra: 'lago', traducaoTupi: 'yara', traducaoYanomami: 'peke', traducaoXavante: 'rapo' },
    { id: 42, palavra: 'árvore', traducaoTupi: 'ibá', traducaoYanomami: 'muka', traducaoXavante: 'noma' },
    { id: 43, palavra: 'mar', traducaoTupi: 'paraná', traducaoYanomami: 'hoima', traducaoXavante: 'kato' },
    { id: 44, palavra: 'campo', traducaoTupi: 'caapuã', traducaoYanomami: 'hima', traducaoXavante: 'dzata' },
    { id: 45, palavra: 'raiz', traducaoTupi: 'ybyra', traducaoYanomami: 'hemo', traducaoXavante: 'toma' },
    { id: 46, palavra: 'cachoeira', traducaoTupi: 'kuti', traducaoYanomami: 'pira', traducaoXavante: 'koma' },
    { id: 47, palavra: 'neve', traducaoTupi: 'ngata', traducaoYanomami: 'hari', traducaoXavante: 'peka' },
    { id: 48, palavra: 'sapo', traducaoTupi: 'opira', traducaoYanomami: 'pue', traducaoXavante: 'hoji' },
    { id: 49, palavra: 'lobo', traducaoTupi: 'guyra', traducaoYanomami: 'takiri', traducaoXavante: 'kaú' },
];

